'use client';
import {useEffect,useRef,useState,useCallback} from 'react';
import {Wheat,Coins,TreePine,Mountain,Sun,Plus,Minus,RotateCw,LocateFixed,ArrowUpRight,ArrowRight,House,Bird,Milk,Scissors,Wind,BookOpen,Check,CheckCheck,X,Pause,Play,HelpCircle,Leaf,Package,MousePointer2,Sparkles,Clock,ChevronDown} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {ANIMALS,TYPES,QUESTS,freshState,restore,perform,capacity,upgradeCost,affordable,progress,revenue,canPlace,seedCost,type State,type Kind,type AnimalKind,type Cost,type Action} from './model';
import type {FarmScene} from './scene';
import {registerFarmTools} from './webmcp';
const SAVE_KEY='harvest-hollow-v1';
const ICONS={house:House,coop:Bird,barn:Milk,sheepfold:Scissors,mill:Wind,field:Wheat};
function Price({cost}:{cost:Cost}){return <span className="price"><span><Coins/>{cost.coins}</span>{cost.wood>0&&<span><TreePine/>{cost.wood}</span>}{cost.stone>0&&<span><Mountain/>{cost.stone}</span>}</span>;}
export default function FarmGame(){
 const [state,setState]=useState<State>(freshState);const ref=useRef(state);const [loaded,setLoaded]=useState(false);const [thumbs,setThumbs]=useState<Record<string,string>>({});const view=useRef<HTMLDivElement>(null);const scene=useRef<FarmScene|null>(null);
 const [selected,setSelected]=useState<string|null>(null);const selectedRef=useRef(selected);const [placing,setPlacing]=useState<Kind|null>(null);const placingRef=useRef(placing);
 const [tab,setTab]=useState('buildings');const [paused,setPaused]=useState(false);const [help,setHelp]=useState(false);const [journal,setJournal]=useState(true);const [status,setStatus]=useState('A little land. A big beginning. Welcome to your farm.');const [failure,setFailure]=useState('');const [saveOK,setSaveOK]=useState(true);
 const act=useCallback((action:Action)=>{const result=perform(ref.current,action);if(result.ok){ref.current=result.state;setState(result.state);}if(result.message)setStatus(result.message);return result;},[]);
 useEffect(()=>{try{const saved=restore(localStorage.getItem(SAVE_KEY));ref.current=saved;setState(saved);}catch{setSaveOK(false);}setLoaded(true);},[]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));setSaveOK(true);}catch{setSaveOK(false);}},[state,loaded]);
 useEffect(()=>{if(!loaded||paused)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now();act({type:'tick',seconds:(now-last)/1000});last=now;},1000);return()=>clearInterval(timer);},[loaded,paused,act]);
 useEffect(()=>{if(!loaded||!view.current)return;let cancelled=false;import('./scene').then(({FarmScene})=>{if(cancelled||!view.current)return;try{scene.current=new FarmScene(view.current,ref.current,{
  pick:(id,x,z)=>{if(placingRef.current){const result=act({type:'build',kind:placingRef.current,x,z});if(result.ok){setPlacing(null);placingRef.current=null;}}else {setSelected(id);selectedRef.current=id;}},
  ready:setThumbs,error:setFailure
 });}catch{setFailure('The 3D view needs WebGL. Enable hardware acceleration in your browser, then reload. You can still manage your farm using the shop and My farm.');}}).catch(()=>setFailure('The farm view could not load. Reload to try again.'));return()=>{cancelled=true;scene.current?.dispose();scene.current=null;};},[loaded,act]);
 useEffect(()=>{selectedRef.current=selected;placingRef.current=placing;scene.current?.update(state,selected,placing);},[state,selected,placing]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPlacing(null);placingRef.current=null;}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{if(matchMedia('(max-width:660px)').matches)setJournal(false);},[]);
 useEffect(()=>{if(!loaded)return;return registerFarmTools(()=>ref.current,act);},[loaded,act]);
 const build=(kind:Kind)=>{setPlacing(kind);placingRef.current=kind;setSelected(null);setStatus('Choose an empty square for your '+TYPES[kind].name.toLowerCase()+'.');};
 const autoBuild=()=>{if(!placing)return;const spots=[];for(let x=-8;x<=8;x+=4)for(let z=-8;z<=8;z+=4)if(canPlace(ref.current,x,z))spots.push({x,z});spots.sort((a,b)=>(Math.abs(a.x)+Math.abs(a.z))-(Math.abs(b.x)+Math.abs(b.z)));if(!spots[0]){setStatus('Your farm is full. Upgrade your existing buildings to grow.');return;}if(act({type:'build',kind:placing,...spots[0]}).ok){setPlacing(null);placingRef.current=null;}};
 const b=state.buildings.find(b=>b.id===selected);const info=b?TYPES[b.kind]:null;const ready=state.buildings.filter(b=>progress(state,b)>=1);const animals=state.buildings.reduce((sum,b)=>sum+b.animals,0);const currentQuest=QUESTS.find(q=>!state.claimed.includes(q.id));const level=Math.floor(state.xp/100)+1;
 const thumb=(key:string,label:string,kind:Kind='house')=>thumbs[key]?<img src={thumbs[key]} alt={label} draggable={false}/>:<span className="thumb-icon">{(()=>{const Icon=ICONS[kind];return <Icon/>;})()}</span>;
 return <main className="farm-app">
  <header className="topbar">
   <div className="brand"><span className="brand-mark"><Wheat/></span><div><h1>Harvest Hollow<span>™</span></h1><p>YOUR LITTLE PATCH OF POSSIBILITY</p></div></div>
   <div className="resources" aria-label="Farm resources"><div className="resource"><span className="resource-icon coin"><Coins/></span><div><small>COINS</small><strong>{state.coins.toLocaleString()}</strong></div></div><div className="resource"><span className="resource-icon wood"><TreePine/></span><div><small>WOOD</small><strong>{state.wood}</strong></div></div><div className="resource"><span className="resource-icon stone"><Mountain/></span><div><small>STONE</small><strong>{state.stone}</strong></div></div></div>
   <div className="top-actions"><button className="icon-button" onClick={()=>setPaused(!paused)} title={paused?'Resume farm':'Pause farm'} aria-label={paused?'Resume farm':'Pause farm'}>{paused?<Play/>:<Pause/>}</button><button className="icon-button" onClick={()=>setHelp(true)} title="How to play" aria-label="How to play"><HelpCircle/></button><span className="avatar">H<span/></span></div>
  </header>
  <div className="world-backdrop"/>
  <div className="scene-wrap" ref={view}/>
  <div className="world-heading"><div className="eyebrow"><span className="live-dot"/> YOUR HOMESTEAD</div><h2>A fresh beginning<span>.</span></h2></div>
  <div className="season"><Sun/><div><strong>Spring <span>·</span> Day {Math.floor(state.elapsed/120)+1}</strong><small>{paused?'A moment of peace — paused':'A lovely day to grow something'}</small></div></div>
  <button className="journal-toggle icon-button" aria-label="Toggle farm journal" aria-expanded={journal} onClick={()=>setJournal(!journal)}><BookOpen/></button>
  {journal&&<aside className="journal">
   <div className="level-card"><span className="level-badge"><Wheat/><b>{level}</b></span><div><span className="eyebrow">FARM LEVEL {level}</span><h3>{level<3?'Budding farmer':level<6?'Growing homestead':'Hollow heartland'}</h3><Progress value={state.xp%100} aria-label="Experience toward next farm level"/><small>{state.xp%100} / 100 XP to level {level+1}</small></div></div>
   <div className="journal-title"><BookOpen size={18}/><h3>The farm journal</h3><span>{state.claimed.length}/4</span></div>
   <p className="journal-sub">Good things start small.</p>
   <div className="quests">{QUESTS.map((q,i)=><div className={'quest '+(state.claimed.includes(q.id)?'complete':'')} key={q.id}><span className={'quest-number '+(q.done(state)?'done':'')}>{q.done(state)?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><div><strong>{q.title}</strong><p>{q.desc}</p>{q.done(state)&&!state.claimed.includes(q.id)?<button className="claim" onClick={()=>act({type:'claim',id:q.id})}>Claim <Coins size={13}/>{q.reward}<ArrowRight size={13}/></button>:<small className="quest-reward">{state.claimed.includes(q.id)?'Reward collected':<><Coins size={12}/> {q.reward} coins</>}</small>}</div></div>)}</div>
   <div className="journal-foot"><Leaf size={20}/><p>{currentQuest?'Follow your journal to earn a little extra along the way.':'Look at you grow! Keep expanding your own little world.'}</p></div>
  </aside>}
  {failure&&<div className="view-error" role="alert"><TreePine/><p>{failure}</p><button onClick={()=>location.reload()} className="primary">Reload farm</button></div>}
  <div className="map-tools"><button className="icon-button" title="Zoom in" aria-label="Zoom in" onClick={()=>scene.current?.zoom(.2)}><Plus/></button><button className="icon-button" title="Zoom out" aria-label="Zoom out" onClick={()=>scene.current?.zoom(-.2)}><Minus/></button><i/><button className="icon-button" title="Rotate view" aria-label="Rotate view" onClick={()=>scene.current?.rotate()}><RotateCw/></button><button className="icon-button" title="Center farm" aria-label="Center farm" onClick={()=>scene.current?.reset()}><LocateFixed/></button></div>
  <div className="scene-caption"><MousePointer2 size={13}/><span>Drag to explore</span><i/>Scroll to zoom<i/><span>Click to manage</span></div>
  {placing&&<div className="placement-banner"><span className="placement-icon"><Plus/></span><div><strong>Place your {TYPES[placing].name.toLowerCase()}</strong><small>Click an empty square on your farm</small></div><button className="primary" onClick={autoBuild}>Auto-place</button><button className="icon-button" onClick={()=>{setPlacing(null);placingRef.current=null;}} aria-label="Cancel placement"><X/></button></div>}
  <section className="shop" aria-label="Farm shop">
   <Tabs value={tab} onValueChange={v=>{if(v)setTab(String(v));}} className="shop-tabs">
    <div className="shop-heading"><TabsList className="shop-nav"><TabsTrigger value="buildings"><House/>Buildings</TabsTrigger><TabsTrigger value="animals"><Bird/>Animals</TabsTrigger><TabsTrigger value="crops"><Wheat/>Crops</TabsTrigger><TabsTrigger value="supplies"><Package/>Supplies</TabsTrigger><TabsTrigger value="farm"><Leaf/>My farm <span className="tab-count">{state.buildings.length}</span></TabsTrigger></TabsList><button className={'harvest-all '+(ready.length?'has-harvest':'')} disabled={!ready.length} onClick={()=>act({type:'collectAll'})}><Wheat size={17}/>Collect all{ready.length>0&&<span>{ready.length}</span>}</button></div>
    <TabsContent value="buildings"><div className="shop-items">{(['coop','barn','sheepfold','mill'] as Kind[]).map(kind=><button key={kind} className={'shop-card '+(placing===kind?'chosen':'')} onClick={()=>build(kind)} disabled={!affordable(state,TYPES[kind].cost)}><div className={'product-art art-'+kind}>{thumb(kind+'1',TYPES[kind].name,kind)}<span className="add-item"><Plus size={13}/></span></div><div className="product-info"><strong>{TYPES[kind].name}</strong><small>{kind==='mill'?'Earn coins from flour':'Room for '+TYPES[kind].capacity+' '+(kind==='coop'?'chickens':kind==='barn'?'cows':'sheep')}</small><Price cost={TYPES[kind].cost}/></div></button>)}<div className="shop-note"><Sparkles/><strong>Built to grow.</strong><p>Every upgrade brings a new look and more possibility.</p><span>3 levels of lovely</span></div></div></TabsContent>
    <TabsContent value="animals"><div className="shop-items">{(Object.keys(ANIMALS) as AnimalKind[]).map(kind=>{const a=ANIMALS[kind],room=state.buildings.filter(b=>b.kind===a.home).reduce((n,b)=>n+capacity(b)-b.animals,0);return <button className="shop-card animal-card" key={kind} onClick={()=>act({type:'buy',kind})} disabled={!room||state.coins<a.price} title={!room?'Build or upgrade a '+TYPES[a.home].name.toLowerCase():a.desc}><div className="product-art">{thumb(kind,a.name,a.home)}<span className="add-item"><Plus size={13}/></span></div><div className="product-info"><strong>{a.name}</strong><small>{room?room+' spaces available':'Needs '+TYPES[a.home].name.toLowerCase()}</small><Price cost={{coins:a.price,wood:0,stone:0}}/></div></button>})}<div className="shop-note"><Bird/><strong>A place to call home.</strong><p>Build a shelter first, then welcome your animals.</p><span>{animals} happy residents</span></div></div></TabsContent>
    <TabsContent value="crops"><div className="shop-items"><button className="shop-card" disabled={!affordable(state,TYPES.field.cost)} onClick={()=>build('field')}><div className="product-art">{thumb('field1','Golden wheat patch','field')}<span className="add-item"><Plus size={13}/></span></div><div className="product-info"><strong>Wheat patch</strong><small>First planting included</small><Price cost={TYPES.field.cost}/></div></button><div className="crop-guide"><div><span>01</span><strong>Plant a little</strong><small>Replant for 8 coins</small></div><ArrowRight/><div><span>02</span><strong>Let it grow</strong><small>Ready in 28 seconds</small></div><ArrowRight/><div><span>03</span><strong>Reap the rewards</strong><small>48+ coins per harvest</small></div></div><div className="shop-note"><Wheat/><strong>Golden opportunities.</strong><p>Upgrade your farmhouse to increase every wheat harvest.</p></div></div></TabsContent>
    <TabsContent value="supplies"><div className="shop-items">{(['wood','stone'] as const).map(kind=><button key={kind} className="shop-card supply-card" disabled={state.coins<50} onClick={()=>act({type:'resource',kind})}><div className="product-art">{kind==='wood'?<TreePine/>:<Mountain/>}<span className="supply-amount">+{kind==='wood'?30:20}</span></div><div className="product-info"><strong>{kind==='wood'?'Timber bundle':'Stone delivery'}</strong><small>For building & upgrades</small><Price cost={{coins:50,wood:0,stone:0}}/></div></button>)}<div className="shop-note"><Package/><strong>Dream it. Build it.</strong><p>Trade your harvest earnings for the materials you need.</p><span>Delivered instantly</span></div></div></TabsContent>
    <TabsContent value="farm"><div className="shop-items farm-list">{state.buildings.map(b=><button className="shop-card" key={b.id} onClick={()=>setSelected(b.id)}><div className="product-art">{thumb(b.kind+b.level,TYPES[b.kind].name,b.kind)}<span className="building-level">L{b.level}</span></div><div className="product-info"><strong>{TYPES[b.kind].name}</strong><small>{TYPES[b.kind].capacity?b.animals+'/'+capacity(b)+' animals':b.kind==='house'?'Your homestead':'Wheat patch'}</small><span className={'farm-status '+(progress(state,b)>=1?'ready':'')}>{progress(state,b)>=1?'Ready to collect':b.kind==='house'?'Manage & upgrade':b.kind==='field'&&!b.planted?'Ready to plant':'Manage'}<ArrowUpRight size={14}/></span></div></button>)}</div></TabsContent>
   </Tabs>
  </section>
  <footer className="statusbar"><span className="game-status" role="status"><span className="live-dot"/>{status}</span><span className={'save-status '+(!saveOK?'save-warning':'')}><CheckCheck size={14}/>{saveOK?'Saved on this device':'Progress cannot be saved in this browser'}</span></footer>
  <Dialog open={!!b} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="building-dialog">{b&&info&&<>
   <div className={'building-hero art-'+b.kind}>{thumb(b.kind+b.level,info.looks[b.level-1],b.kind)}<span className="tier-badge">LEVEL {b.level} / 3</span></div>
   <div className="building-body"><div className="eyebrow">YOUR HOMESTEAD</div><DialogTitle className="building-name">{info.name}</DialogTitle><DialogDescription>{info.looks[b.level-1]} · {info.desc}</DialogDescription>
   {info.capacity>0&&<div className="building-stats"><div><small>HAPPY RESIDENTS</small><strong>{b.animals} <span>/ {capacity(b)}</span></strong></div><div><small>{info.product.toUpperCase()} EVERY {info.period}s</small><strong className="income"><Coins/>{revenue(state,b)}</strong></div></div>}
   {info.period>0&&<div className="production">{b.kind==='field'&&!b.planted?<button className="primary wide" onClick={()=>act({type:'plant',id:b.id})} disabled={state.coins<seedCost(state)}><Wheat size={17}/>Plant wheat <span>{seedCost(state)?'8 coins':'Gifted seeds · free'}</span></button>:info.capacity>0&&!b.animals?<button className="primary wide" onClick={()=>{setSelected(null);setTab('animals');}}><Bird size={17}/>Buy your first animal<ArrowRight size={17}/></button>:<><div className="production-label"><span>{progress(state,b)>=1?'Ready for collection':info.product+' are on the way'}</span><strong>{progress(state,b)>=1?'All grown!':Math.ceil(info.period*(1-progress(state,b)))+'s'}</strong></div><Progress value={progress(state,b)*100} aria-label={info.product+' production'}/><button className="primary wide" disabled={progress(state,b)<1} onClick={()=>act({type:'collect',id:b.id})}><Wheat size={17}/>Collect {info.product.toLowerCase()}<span>+{revenue(state,b)} coins</span></button></>}</div>}
   {b.kind==='house'&&<div className="house-bonus"><Wheat/><span>Every wheat harvest earns <strong>{(b.level-1)*20}% extra coins</strong>.</span></div>}
   <div className="upgrade-section"><div className="upgrade-title"><Sparkles size={18}/><h3>{b.level<3?'A little room to grow':'Your finest work'}</h3><span>{b.level<3?'LEVEL '+(b.level+1):'MAX LEVEL'}</span></div>
   <div className="upgrade-preview">{thumb(b.kind+Math.min(3,b.level+1),info.looks[Math.min(2,b.level)],b.kind)}<div><strong>{info.looks[Math.min(2,b.level)]}</strong><p>{b.level===3?'A fully upgraded part of your homestead.':info.capacity?'Room for '+info.capacity*(b.level+1)+' animals · Better production':b.kind==='house'?'New roof, extra wing · +20% crop income':'A new look · Higher harvest value'}</p>{b.level<3&&<Price cost={upgradeCost(b)}/>}</div></div>
   {b.level<3?<button className="primary wide upgrade-button" disabled={!affordable(state,upgradeCost(b))} onClick={()=>act({type:'upgrade',id:b.id})}><Sparkles size={16}/>Upgrade to level {b.level+1}<ArrowUpRight size={17}/></button>:<div className="max-level"><CheckCheck size={16}/>Beautifully complete</div>}
   {b.level<3&&!affordable(state,upgradeCost(b))&&<p className="insufficient">Collect a harvest or visit Supplies for the materials you need.</p>}</div>
   </div>
  </>}</DialogContent></Dialog>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><span className="help-mark"><Wheat/></span><DialogTitle>Welcome to the Hollow.</DialogTitle><DialogDescription>Your little farm grows one good day at a time.</DialogDescription><ol><li><strong>Start with a harvest.</strong> Click the golden wheat or Collect all to earn your first coins. Replant for 8 coins.</li><li><strong>Build a home.</strong> Pick a building in the shop, then click an empty farm square. Auto-place can choose a square for you.</li><li><strong>Meet your animals.</strong> Chickens need a coop, cows need a barn, and sheep need a pasture. They produce without feeding chores.</li><li><strong>Watch it change.</strong> Click any building to collect its produce or upgrade. Every level adds a new look and better production.</li></ol><p className="help-saving">Progress saves automatically in this browser. Time advances while the game is open; Pause takes a break. Farm levels and journal milestones give bonus supplies.</p><button className="primary wide" onClick={()=>setHelp(false)}>Let's grow something<ArrowRight size={17}/></button></DialogContent></Dialog>
 </main>;
}
